/** Shared UI copy (mirrors Android `core/ui` strings). */
export const uiStrings = {
  loading: 'Loading',
  bookmark: 'Bookmark',
  unbookmark: 'Remove bookmark',
  unreadDot: 'Unread',
  cardTapAction: 'Open article',
  topicFollowed: (name: string) => `${name} is followed`,
  topicNotFollowed: (name: string) => `${name} is not followed`,
  metadataWithType: (date: string, type: string) => `${date} • ${type}`,
  bookmarkNoteDialogTitle: 'Add a note?',
  bookmarkNoteDialogLabel: 'Note (optional)',
  bookmarkNoteDialogPlaceholder: 'Why did you save this?',
  bookmarkNoteCharactersRemaining: (count: number) =>
    `${count} characters remaining`,
  bookmarkNoteSave: 'Save',
  bookmarkNoteSkip: 'Skip',
  bookmarkNoteEditorTitle: 'Edit note',
  bookmarkNoteEditorLabel: 'Note',
  bookmarkNoteEditorSave: 'Save',
  bookmarkNoteEditorCancel: 'Cancel',
  bookmarkNoteEditorDelete: 'Delete note',
  bookmarkHasNote: 'Has note',
  bookmarkNoteContentDescription: 'Edit bookmark note',
  offlineSnackbar: "You're offline. Showing saved content.",
  emptyStateDefaultTitle: 'Nothing here yet',
  emptyStateDefaultDescription: 'Check back later for new content.',
  selectItem: 'Select item',
} as const;
